spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/liuyun
      username: root
      password: 0830
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: ["file:D:/liuyun/static/", "classpath:/static/"]

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.liuyun.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl